// Qualified against codex-cli 0.155.0-alpha.16.4 generate-ts --experimental.
// Every installed notification and ThreadItem has an explicit compact policy.
export type CompactPolicy =
  | "wake_typed"
  | "accumulate_typed"
  | "activity_only"
  | "ignore_compact"
  | { kind: "diagnostic_passthrough"; wake: boolean };

const diagnostic = (wake: boolean): CompactPolicy => ({ kind: "diagnostic_passthrough", wake });

export const NOTIFICATION_POLICIES: Readonly<Record<string, CompactPolicy>> = {
  "error": "wake_typed",
  "thread/started": "accumulate_typed",
  "thread/status/changed": "accumulate_typed",
  "thread/archived": diagnostic(false),
  "thread/deleted": diagnostic(true),
  "thread/unarchived": diagnostic(false),
  "thread/closed": diagnostic(true),
  "thread/reverted": diagnostic(true),
  "skills/changed": "ignore_compact",
  "thread/name/updated": "ignore_compact",
  "thread/attachment/updated": "ignore_compact",
  "thread/goal/updated": diagnostic(true),
  "thread/goal/cleared": diagnostic(true),
  "thread/queue/changed": diagnostic(true),
  "project/changed": "ignore_compact",
  "thread/project/updated": "ignore_compact",
  "thread/environment/connected": diagnostic(true),
  "thread/environment/disconnected": diagnostic(true),
  "thread/settings/updated": "accumulate_typed",
  "thread/tokenUsage/updated": "ignore_compact",
  "turn/started": "accumulate_typed",
  "hook/started": diagnostic(false),
  "turn/completed": "wake_typed",
  "hook/completed": diagnostic(false),
  "turn/diff/updated": "activity_only",
  "turn/plan/updated": "accumulate_typed",
  "item/started": "accumulate_typed",
  "item/autoApprovalReview/started": "wake_typed",
  "item/autoApprovalReview/completed": "wake_typed",
  "autoApprovalReview/strictReviewRequired": "wake_typed",
  "item/completed": "accumulate_typed",
  "rawResponseItem/completed": "ignore_compact",
  "rawResponse/completed": "ignore_compact",
  "item/agentMessage/delta": "activity_only",
  "item/plan/delta": "activity_only",
  "command/exec/outputDelta": "activity_only",
  "process/outputDelta": "activity_only",
  "process/exited": "accumulate_typed",
  "item/commandExecution/outputDelta": "activity_only",
  "item/commandExecution/terminalInteraction": diagnostic(true),
  "item/fileChange/outputDelta": "activity_only",
  "item/fileChange/patchUpdated": "activity_only",
  "serverRequest/resolved": "activity_only",
  "item/mcpToolCall/progress": "activity_only",
  "mcpServer/oauthLogin/completed": diagnostic(true),
  "mcpServer/startupStatus/updated": "accumulate_typed",
  "mcpServer/event/stream/notification": diagnostic(false),
  "account/updated": "ignore_compact",
  "account/rateLimits/updated": "ignore_compact",
  "app/list/updated": "ignore_compact",
  "remoteControl/status/changed": "ignore_compact",
  "externalAgentConfig/import/progress": "ignore_compact",
  "externalAgentConfig/import/completed": diagnostic(false),
  "fs/changed": "ignore_compact",
  "item/reasoning/summaryTextDelta": "activity_only",
  "item/reasoning/summaryPartAdded": "activity_only",
  "item/reasoning/textDelta": "activity_only",
  "thread/compacted": diagnostic(false),
  "model/rerouted": "wake_typed",
  "model/verification": "wake_typed",
  "modelProvider/authRecoveryStarted": diagnostic(true),
  "modelProvider/authRecoveryCompleted": diagnostic(true),
  "turn/moderationMetadata": diagnostic(true),
  "model/safetyBuffering/updated": "wake_typed",
  "warning": "wake_typed",
  "guardianWarning": "wake_typed",
  "deprecationNotice": diagnostic(false),
  "configWarning": "wake_typed",
  "fuzzyFileSearch/sessionUpdated": "ignore_compact",
  "fuzzyFileSearch/sessionCompleted": "ignore_compact",
  "thread/realtime/started": diagnostic(false),
  "thread/realtime/itemAdded": diagnostic(false),
  "thread/realtime/item/started": diagnostic(false),
  "thread/realtime/item/transcript/delta": "ignore_compact",
  "thread/realtime/item/completed": diagnostic(false),
  "thread/realtime/transcript/delta": "ignore_compact",
  "thread/realtime/transcript/done": diagnostic(false),
  "thread/realtime/outputAudio/delta": "ignore_compact",
  "thread/realtime/sdp": "ignore_compact",
  "thread/realtime/error": diagnostic(true),
  "thread/realtime/closed": diagnostic(false),
  "windows/worldWritableWarning": "wake_typed",
  "windowsSandbox/setupCompleted": diagnostic(false),
  "account/login/completed": "ignore_compact",
};

export const ITEM_POLICIES: Readonly<Record<string, CompactPolicy>> = {
  userMessage: "activity_only",
  hookPrompt: "activity_only",
  agentMessage: "wake_typed",
  functionCallOutput: "activity_only",
  plan: "accumulate_typed",
  reasoning: "activity_only",
  commandExecution: "accumulate_typed",
  fileChange: "accumulate_typed",
  mcpToolCall: "accumulate_typed",
  dynamicToolCall: "accumulate_typed",
  collabAgentToolCall: "accumulate_typed",
  subAgentActivity: "accumulate_typed",
  webSearch: "accumulate_typed",
  imageView: "activity_only",
  sleep: "accumulate_typed",
  imageGeneration: "accumulate_typed",
  enteredReviewMode: "wake_typed",
  exitedReviewMode: "wake_typed",
  contextCompaction: "activity_only",
};
